
blog5 = Blog.create(title: "Rails Generators", link: "https://medium.com/@melissafunk85/rails-generators-d13a4a879e28", image: "https://miro.medium.com/max/700/1*-4Zn-s5Ro0Oft6VcKLfXWQ.png", minutes: 4, date: "November 1st, 2021")
blog4 = Blog.create(title: "Why I Joined a Coding Bootcamp", link: "https://medium.com/@melissafunk85/why-i-joined-a-coding-bootcamp-46931e5f0b72", image: "https://miro.medium.com/max/700/1*_1xUMTrBKrDN3uYChEb7sA.jpeg", minutes: 5, date: "October 10th, 2021")
blog3 = Blog.create(title: "JavaScript Array Methods", link: "https://medium.com/@melissafunk85/javascript-array-methods-2783698cd501", image: "https://miro.medium.com/max/700/1*F4P7fHCcyHWjtMoGb8onRw.png", minutes: 4, date: "September 14th, 2021")
blog2 = Blog.create(title: "Planning a Coding Project", link: "https://medium.com/@melissafunk85/planning-a-coding-project-bc8f59d01c07", image: "https://miro.medium.com/max/700/1*Zu_PI_sUWu0x1r0d6MeFPQ.png", minutes: 4, date: "September 5th, 2021")
blog1 = Blog.create(title: "Changing Images Using Hover in CSS", link: "https://medium.com/@melissafunk85/changing-images-using-hover-97af51c0d8d0", image: "https://miro.medium.com/max/700/1*whMuSZ_AlAQx1KSVVG9p3g.png", minutes: 4, date: "August 18th, 2021")

project1 = Project.create(title: "Hot Dog Lover", link: "https://www.hotdoglover.app/", youtube: "https://youtu.be/a4xBINdvanU", github: "https://github.com/MelissaFunk/hot-dog-lover-app", description: "Explore hot dog restaurants around San Francisco! Users can login/create an account to view restaurants and create a personalized hot dog. For the hot dog lover at heart ❤️ 🌭 ❤️", image: "https://i.imgur.com/R9JYj3d.png")
project2 = Project.create(title: "Hot Takes", link: "https://www.hottakes.app/", github: "https://github.com/MelissaFunk/hot-takes", description: "A hot takes app where users can log their top 5 in a given category.", image: "https://i.imgur.com/VJSFAge.png")
project3 = Project.create(title: "Gilmore Girls Trivia", link: "http://www.gilmoretrivia.com/", github: "https://github.com/MelissaFunk/gg-trivia", description: "Users answer a series of trivia questions about the gift that is Gilmore Girls the TV show. At the end, users can see the top 5 trivia scores by all users.", image: "https://i.imgur.com/JjC3UKP.png")

aboutcard1 = AboutCard.create(image: "https://cdn-icons-png.flaticon.com/128/1152/1152946.png", title: "Ambitious", description: "Passionate about learning and self-development.")
aboutcard2 = AboutCard.create(image: "https://cdn-icons-png.flaticon.com/128/1632/1632870.png", title: "Dedicated", description: "Persistant and focused about results.")
aboutcard3 = AboutCard.create(image: "https://cdn-icons-png.flaticon.com/128/1584/1584892.png", title: "Quick", description: "Fast-paced learner and time-sensitive.")
aboutcard4 = AboutCard.create(image: "https://cdn-icons-png.flaticon.com/128/1693/1693056.png", title: "Organized", description: "Penchant for details and writing clean code.")
